services:
  documents-api:
    build:
      context: .
      dockerfile: DocumentsAPI/Dockerfile
    ports:
      - 5000:8080
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      RabbitMqSettings__HostName: "rabbitmq"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      rabbitmq:
        condition: service_healthy

  catalog-api:
    build:
      context: .
      dockerfile: CatalogAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"

  customers-api:
    build:
      context: .
      dockerfile: CustomersAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"

  orders-api:
    build:
      context: .
      dockerfile: OrdersAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"

  documents-generator:
    build:
      context: .
      dockerfile: DocumentsGenerator/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      CustomersApiUrl: "http://customers-api:8080"
      CatalogApiUrl: "http://catalog-api:8080"
      OrdersApiUrl: "http://orders-api:8080"
      RabbitMqSettings__HostName: "rabbitmq"
      BlobStorageConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      rabbitmq:
        condition: service_healthy
