services:
  migrations-runner:
    build:
      context: .
      dockerfile: src/MigrationsRunner/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      database:
        condition: service_healthy

  documents-api:
    build:
      context: .
      dockerfile: src/DocumentsAPI/Dockerfile
    ports:
      - 5000:8080
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      RabbitMqSettings__HostName: "rabbitmq"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrations-runner:
        condition: service_completed_successfully

  catalog-api:
    build:
      context: .
      dockerfile: src/CatalogAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      migrations-runner:
        condition: service_completed_successfully

  customers-api:
    build:
      context: .
      dockerfile: src/CustomersAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      migrations-runner:
        condition: service_completed_successfully

  orders-api:
    build:
      context: .
      dockerfile: src/OrdersAPI/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      migrations-runner:
        condition: service_completed_successfully

  documents-generator:
    build:
      context: .
      dockerfile: src/DocumentsGenerator/Dockerfile
    environment:
      ConnectionStrings__Database: "Server=database,1433;Database=master;User Id=SA;Password=<YourStrong@Passw0rd>;TrustServerCertificate=True"
      CustomersApiUrl: "http://customers-api:8080/customers/"
      CatalogApiUrl: "http://catalog-api:8080/products/"
      OrdersApiUrl: "http://orders-api:8080/orders/"
      RabbitMqSettings__HostName: "rabbitmq"
      BlobStorageConnectionString: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;"
      OpenTelemetrySettings__Endpoint: "http://otel-collector:4317"
    depends_on:
      rabbitmq:
        condition: service_healthy
      migrations-runner:
        condition: service_completed_successfully
    
  prometheus:
    volumes:
      - ./Infrastructure/Prometheus/prometheus.yml:/prometheus/prometheus.yml
