services:
  
  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus
      - ./Infrastructure/Prometheus/prometheus.local.yml:/prometheus/prometheus.yml
    command:
      - "--web.enable-remote-write-receiver" # Enable OtelCollector to push metrics

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./Infrastructure/Grafana/datasources:/etc/grafana/provisioning/datasources
      - ./Infrastructure/Grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./Infrastructure/Grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana

  loki:
    image: grafana/loki
    user: root
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./Infrastructure/Grafana/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/tmp/loki/

  otel-collector:
    # using contrib so it includes the loki exporter and service graph exporter
    image: otel/opentelemetry-collector-contrib
    command: --config=/etc/otel-collector-config.yaml
    volumes:
      - ./Infrastructure/OtelCollector/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      #- 8889:8889   # Prometheus exporter metrics
      - 4317:4317   # OTLP gRPC receiver

  jaeger:
    image: jaegertracing/all-in-one:1.52
    ports:
      - 4317 # Accept OTLP over GRPC
      - 5778 # Serve configs
      - 16686:16686 # Serve frontend

  seq:
    image: datalust/seq:2023.4
    ports:
      - 3010:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH="password"
    volumes:
      - seq-data:/data


volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  seq-data:
    