// <auto-generated />
using System;
using CatalogAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogAPI.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20240103154028_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogAPI.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ba58a44-ead2-4efa-96dd-b789101953e6"),
                            Description = "May contain traces of lighters and razors",
                            Name = "Pen"
                        },
                        new
                        {
                            Id = new Guid("9323c4f1-8a0b-4dda-9272-a96b4c59313f"),
                            Description = "Wooden and yellow, Green Lantern's worst enemy",
                            Name = "Pencil"
                        },
                        new
                        {
                            Id = new Guid("e7e45871-5885-462f-b6e7-85dec42e037e"),
                            Description = "Careful writing names in it, anything could happen",
                            Name = "Notebook"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
