global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "documents-api"
    static_configs:
      - targets: ["host.docker.internal:5192"]

  - job_name: "catalog-api"
    static_configs:
      - targets: ["host.docker.internal:5141"]

  - job_name: "customers-api"
    static_configs:
      - targets: ["host.docker.internal:5217"]

  - job_name: "orders-api"
    static_configs:
      - targets: ["host.docker.internal:5164"]