global:
  scrape_interval: 2s

scrape_configs:
  - job_name: "documents-api"
    static_configs:
      - targets: ["host.docker.internal:5192"]

  - job_name: "catalog-api"
    static_configs:
      - targets: ["host.docker.internal:5141"]

  - job_name: "customers-api"
    static_configs:
      - targets: ["host.docker.internal:5217"]

  - job_name: "orders-api"
    static_configs:
      - targets: ["host.docker.internal:5164"]
  
  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - 'rmq0:15692'
          - 'rmq1:15692'
          - 'rmq2:15692'
          - 'rmq0-dist-tls:15692'
          - 'rmq1-dist-tls:15692'
          - 'rmq2-dist-tls:15692'
          - 'rmq0-qq:15692'
          - 'rmq1-qq:15692'
          - 'rmq2-qq:15692'
          - 'rmq0-dist-metrics:15692'
          - 'rmq1-dist-metrics:15692'
          - 'rmq2-dist-metrics:15692'