global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "documents-api"
    static_configs:
      - targets: ["documents-api:8080"]

  - job_name: "catalog-api"
    static_configs:
      - targets: ["catalog-api:8080"]

  - job_name: "customers-api"
    static_configs:
      - targets: ["customers-api:8080"]

  - job_name: "orders-api"
    static_configs:
      - targets: ["orders-api:8080"]

  - job_name: 'rabbitmq-server'
    static_configs:
      - targets: ["rabbitmq:15692"]