receivers:
  otlp:
    protocols:
      grpc:

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"    
    tls:
      insecure: true
      
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write

  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
    logs:
      receivers: [otlp]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
      