receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"    
    tls:
      insecure: true
      
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
  
  otlphttp:
    endpoint: "http://seq:5341/ingest/otlp"
    tls:
      insecure: true

  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]
    logs:
      receivers: [otlp]
      exporters: [loki, otlphttp]
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
      