{
 "title": "Application Logs / Info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Documents generated per product",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documentsgenerator_products_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Documents generated per customer",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "documentsgenerator_customers_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DocumentsAPI logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"DocumentsAPI\"} | json | line_format `{{.level}} - {{.body}}`"
    }
   ]
  },
  {
   "title": "DocumentsGenerator logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"DocumentsGenerator\"} | json | line_format `{{.level}} - {{.body}}`"
    }
   ]
  },
  {
   "title": "CatalogAPI logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"CatalogAPI\"} | json | line_format `{{.level}} - {{.body}}`"
    }
   ]
  },
  {
   "title": "CustomersAPI logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{job=\"CustomersAPI\"} | json | line_format `{{.level}} - {{.body}}`"
    }
   ]
  },
  {
   "title": "OrdersAPI logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"OrdersAPI\"} | json | line_format `{{.level}} - {{.body}}`"
    }
   ]
  }
 ]
}