// <auto-generated />
using System;
using CustomersAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomersAPI.Migrations
{
    [DbContext(typeof(CustomersContext))]
    partial class CustomersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomersAPI.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87c77822-d53d-4db1-8e66-468e28102456"),
                            Name = "Kevin Lluch"
                        },
                        new
                        {
                            Id = new Guid("3f617303-3844-4403-9017-4fb0bd0ac827"),
                            Name = "Pedro Monge"
                        },
                        new
                        {
                            Id = new Guid("c654b145-1a4a-43b4-a741-87b186554edc"),
                            Name = "Francisco Rubio"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
